### ISSUE TITLE
To Code

### ISSUE THREAD

**Issue by Mlnd95** [teamvilbel/SoQua_Projekt_PMS#2]
### GUI 

Settings.fxml
- [x] Dateipicking muss funktionieren
- [x] Berichterzeugung muss funktionieren
- [x] Seitenwechsel von "Settings" zu "Bericht" und zurück.
- [x] Dropdownmenü für Datum und Medikament mit CSV Datei Inhalten verknüpfen.
- [x] Filterung aufgrund von Auswahlmöglichkeiten in Dropdownmenüs
       Bedeutet: Nach Tag, nach Medikament und nach Tag & Medikament

Bericht.fxml
- [x] Öffnen von Diagramm über "Diagramm erzeugen" Button
- [x] Wechsel von "Bericht.fxml" zurück zu "Settings.fxml" über "Zurück" Button
- [x] Einfügen von Tupeln aus CSV Datei in "TablePane"
- [x] Filterung von Tupeln über zuvor in "Settings.fxml" gesetzte Filter (Dropdownmenüs)
- [x] Anzeigen von Gesamtkosten/Gesamte Verschreibungen pro Monat in Textfeld unterhalb der 
      "Tabelle"

Diagramm.fxml
- [x] Erzeugung des Diagramms in Abhängigkeit von zuvor gewählten Filtern
- [x] Schließen von Diagramm.fxml
~~Wechsle Diagramm Ansicht von Gesamtkosten zu Einzelkosten  in Abhängigkeit der zuvor 
      gewählten Filter~~

**Comment by SirMoM** [comment]
Done ?
@Mlnd95 
@jeanpauledoh 
@aMJenger
